### ISSUE TITLE
[항공권 발급 관리] 항공권 발급 < "이름을 입력세요:

### ISSUE THREAD

**Issue by l2chmnl** [ssg-240304-java2/OOP-showmethemoney#17]
**문제 발생 상황**
항공권 발급 > "이름을 입력하세요 : " 이후 2번 입력해야함

**문제 상황 재현**
1. Run 에서 main 시작
2. 1. 항공권 발급 입력
3. 콘솔창에 '이름을 입력하세요 : ' 출력
4. 첫 입력 or 두 번째 입력에 이름을 2번 입력해야 하는 현상 확인

**해결을 위한 행동**

**사진첨부(필요하면)**
![firstBugInputName](https://github.com/ssg-240304-java2/OOP-showmethemoney/assets/162394517/ee7d3535-fae4-4b58-9ca3-fe6fb01a69fc)

**테스트 환경**
 - OS: KingGod Window10pro
 - Browser 
 - Version JDK Temurin 17

**Comment by lucinda96** [comment]
2명이상 정보 등록 버그 수정 완료 
<img width="280" alt="image" src="https://github.com/ssg-240304-java2/OOP-showmethemoney/assets/90363122/a76bbd80-a59d-4c66-ae3e-f3fff469a672">
