### ISSUE TITLE
[항공권발급관리]도착지와 항공권티켓번호 자리가 바뀜

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/OOP-showmethemoney#18]
**문제 발생 상황**
도착지와 항공권티켓번호 자리가 바뀜

**문제 상황 재현**
1. 시스템 실행
2. 항공권 정보 등록
3. 항공권 정보 표시 -> 에러 발생

**해결을 위한 행동**
toString 메소드 자리 위치 변경

**사진첨부(필요하면)**
![스크린샷 2024-04-04 오후 5 52 24](https://github.com/ssg-240304-java2/OOP-showmethemoney/assets/156323937/2081fc20-2505-437b-9e55-0b2fdeb22b62)

**Comment by l2chmnl** [comment]
finally fixed them
