### ISSUE TITLE
버그리포트작성

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/OOP-showmethemoney#2]
**문제 발생 상황**
버튼클릭시 동작안함

**문제 상황 재현**
1. 회원가입화면 표시
2. 아이디, 비밀번호입력
3. 로그인버튼 클릭
4. 동작없음

**해결을 위한 행동**
이벤트 연결이 필요

**테스트 환경**
 - OS: [e.g. iOS] window
 - Browser [e.g. chrome, safari] chrome

**Comment by l2chmnl** [comment]
확인 결과 일시적 오작동으로 판명났습니다.

**Comment by zZerorok** [comment]
잘 해결 하셨네요 ^^

**Comment by zZerorok** [comment]
이거 어떻게 해결하죠??
