### ISSUE TITLE
[항공권 발급 관리]이름 수정하기

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/OOP-showmethemoney#20]
**문제 발생 상황**
항공권 정보 변경 (이름 변경 문제)

**문제 상황 재현**
항공권 수정 사항 (이름 수정하기)
검색할 이름을 입력하세요: 2번 출력
도착지 선택창으로 이동

**해결을 위한 행동**
검색할 이름 입력 1번 받고 검증 후 도착지 선택창이 아닌 이름 수정으로 넘어가기

**사진첨부(필요하면)**
![스크린샷 2024-04-04 오후 9 41 12](https://github.com/ssg-240304-java2/OOP-showmethemoney/assets/156323937/c56c2120-9e43-4a3d-8601-a728a60a712d)

**Comment by l2chmnl** [comment]
mission complete
