### ISSUE TITLE
[항공권 발급 관리] 항공권 정보 표시

### ISSUE THREAD

**Issue by l2chmnl** [ssg-240304-java2/OOP-showmethemoney#5]
**기능 요약**
- 항공권 정보 표시

**기능 설명**
- 저장되어 있는 모든 승객들의 
항공권 번호, 이름, 출발지, 도착지 출력하기

**할일목록**
- [x] 저장한 내용 출력하는 메서드 만들기.
- [x] sout""" 해서 깔끔하게 꾸며보기

**Comment by zZerorok** [comment]
작업 완료
