### ISSUE TITLE
[항공권 발급 관리] 항공권 발급

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/OOP-showmethemoney#6]
**기능 요약**
- 항권권 발급에 필요한 정보를 입력받아 항공권 발급

**기능 설명**
- 항공권발급에 필요한 인적 정보와 항공권 정보를 입력받은 후 저장

**할일 목록**
- [x] Random으로 항공권 번호 발급
- [x] 이름 정규화 식으로 영문만 들어왔는지 확인
- [x] 도착지가 선택지 내에 있는지 확인
- [x] 입력받은 인적저보와 항공권정보로 저장

**Comment by zZerorok** [comment]
작업 완료
